device:
  num_workers: 8
  pin_memory: True

train:
  pattern_name: "cardiomegaly"
  step_size: 0.00001
  opt_lr: 0.000001
  opt_spurious_lr: 0.00001
  opt_target_lr: 0.000001
  weight_decay: 0.00001
  MI_para: 10
  target_para: 1
  spurious_para: 10
  rev_para: 0.1
  epochs: 100
  batch_size: 32
  save_interval: 1
  target_classes: 1
  train_path: "./csvs/Race_Cardiomegaly_20.csv"
  test_path: "./csvs/Race_Cardiomegaly_20.csv"

meta:
  pretrain_mask_weight: "args["meta"]["pretrain_mask_weight"]"
  pretrain_spurious_weight: "args['meta']["pretrain_spurious_weight"]"
  weight_dir: "weight"
  saveAllimage: False
  masked_img_dir: "save_image"
  spurious_type: "race"
  testing_epoch: 10

